package ru.vniizht.asuter.autotest.electrical.schema;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import ru.vniizht.asuter.autotest.CommonOps;

import java.io.IOException;

import static ru.vniizht.asuter.autotest.ValidationHelper.checkTitle;
import static ru.vniizht.asuter.autotest.ValidationHelper.checkValue;

public class DcSchemaTest {
    private WebDriver driver;
    private final Logger logger = LoggerFactory.getLogger(DcSchemaTest.class);

    @Before
    public void setUp() {
        driver = new ChromeDriver();
        driver.manage().window().minimize();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void dcSchema() {
        CommonOps.setupAndLogin(driver);

        logger.info("Переход к схеме");
        navigateToSchema();

        WebElement feederConnectionPointInput = driver.findElement(
                By.cssSelector("div:nth-child(2) > .Fiders__fiderCoordinate--I5GNC > .commonStyles__justField--18VJk")
        );
        feederConnectionPointInput.clear();
        feederConnectionPointInput.sendKeys("1200");
        driver.findElement(By.tagName("h3")).click(); // убрать фокус с feederConnectionPointInput

        checkValue(feederConnectionPointInput, "1200");
        checkTitle(feederConnectionPointInput, " Должно быть не более 1100");
        CommonOps.wait(10);
    }

    private void navigateToSchema() { // Generated by Selenium IDE
        driver.get("http://asuter-dev.vniizht.lan/database");
        driver.findElement(By.cssSelector(".MuiTableRow-root:nth-child(5) > .MuiTableCell-root:nth-child(3)")).click();
        driver.findElement(By.cssSelector(".MuiTableRow-root:nth-child(5) > .MuiTableCell-root:nth-child(3)")).click();
        {
            WebElement element = driver.findElement(By.cssSelector(".MuiTableRow-root:nth-child(5) > .MuiTableCell-root:nth-child(3)"));
            Actions builder = new Actions(driver);
            builder.doubleClick(element).perform();
        }
        driver.findElement(By.cssSelector(".MuiTableRow-hover:nth-child(1) > .MuiTableCell-root:nth-child(3)")).click();
        driver.findElement(By.cssSelector(".MuiTableRow-hover:nth-child(1) > .MuiTableCell-root:nth-child(3)")).click();
        {
            WebElement element = driver.findElement(By.cssSelector(".MuiTableRow-hover:nth-child(1) > .MuiTableCell-root:nth-child(3)"));
            Actions builder = new Actions(driver);
            builder.doubleClick(element).perform();
        }
        driver.findElement(By.cssSelector(".MuiTableRow-hover:nth-child(1) > .MuiTableCell-root:nth-child(3)")).click();
        driver.findElement(By.cssSelector(".MuiTableRow-hover:nth-child(1) > .MuiTableCell-root:nth-child(3)")).click();
        {
            WebElement element = driver.findElement(By.cssSelector(".MuiTableRow-hover:nth-child(1) > .MuiTableCell-root:nth-child(3)"));
            Actions builder = new Actions(driver);
            builder.doubleClick(element).perform();
        }
        driver.findElement(By.cssSelector(".MuiTableCell-body:nth-child(3)")).click();
        driver.findElement(By.cssSelector(".MuiTableCell-body:nth-child(3)")).click();
        {
            WebElement element = driver.findElement(By.cssSelector(".MuiTableCell-body:nth-child(3)"));
            Actions builder = new Actions(driver);
            builder.doubleClick(element).perform();
        }
        driver.findElement(By.cssSelector(".card:nth-child(3) .row")).click();
        driver.findElement(By.id("0")).click();
        {
            WebElement element = driver.findElement(By.id("0"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        driver.findElement(By.cssSelector(".Fiders__row--GHIuy:nth-child(2)")).click();
        driver.findElement(By.cssSelector(".Fiders__row--GHIuy:nth-child(2)")).click();
    }
}
